/***************************************************************************
 *     Copyright (c) 1999-2006, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_usb_ohci1.h $
 * $brcm_Revision: Hydra_Software_Devel/2 $
 * $brcm_Date: 3/17/06 7:23p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Mar  7 11:08:38 2006
 *                 MD5 Checksum         81cd4105847969e90c5b929a8fe93d36
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.006
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/3560/rdb/b0/bchp_usb_ohci1.h $
 * 
 * Hydra_Software_Devel/2   3/17/06 7:23p cttok
 * PR20284: new RDB header files to 3560
 * 
 * Hydra_Software_Devel/1   10/21/05 1:55p jasonh
 * PR 17692: Initial version
 *
 ***************************************************************************/

#ifndef BCHP_USB_OHCI1_H__
#define BCHP_USB_OHCI1_H__

/***************************************************************************
 *USB_OHCI1 - USB OHCI 2 Control Registers
 ***************************************************************************/
#define BCHP_USB_OHCI1_HcRevision                0x004c0500 /* Host Controller Revision Register */
#define BCHP_USB_OHCI1_HcControl                 0x004c0504 /* Host Controller Control Register */
#define BCHP_USB_OHCI1_HcCommandStatus           0x004c0508 /* Host Controller Command Status Register */
#define BCHP_USB_OHCI1_HcInterruptStatus         0x004c050c /* Host Controller Interrupt Status Register */
#define BCHP_USB_OHCI1_HcInterruptEnable         0x004c0510 /* Host Controller Interrupt Enable Register */
#define BCHP_USB_OHCI1_HcInterruptDisable        0x004c0514 /* Host Controller Interrupt Disable Register */
#define BCHP_USB_OHCI1_HcHCCA                    0x004c0518 /* Host Controller Communication Area Register */
#define BCHP_USB_OHCI1_HcPeriodCurrentED         0x004c051c /* Current Isochronous or Interrupt Endpoint Descriptor Register */
#define BCHP_USB_OHCI1_HcControlHeadED           0x004c0520 /* First Endpoint Descriptor of the Control List */
#define BCHP_USB_OHCI1_HcControlCurrentED        0x004c0524 /* Current Endpoint Descriptor of the Control List */
#define BCHP_USB_OHCI1_HcBulkHeadED              0x004c0528 /* First Endpoint Descriptor of the Bulk List */
#define BCHP_USB_OHCI1_HcBulkCurrentED           0x004c052c /* Current Endpoint Descriptor of the Bulk List */
#define BCHP_USB_OHCI1_HcDoneHead                0x004c0530 /* Last Completed Transfer Descriptor Added to the Done Queue */
#define BCHP_USB_OHCI1_HcFmInterval              0x004c0534 /* Frame Bit Time Interval Register */
#define BCHP_USB_OHCI1_HcFmRemaining             0x004c0538 /* Bit Time Remaining in the Current Frame */
#define BCHP_USB_OHCI1_HcFmNumber                0x004c053c /* Frame Number Register */
#define BCHP_USB_OHCI1_HcPeriodicStart           0x004c0540 /* Register to Start Processing the Periodic List */
#define BCHP_USB_OHCI1_HcLSThreshold             0x004c0544 /* LS Packet Threshold Register */
#define BCHP_USB_OHCI1_HcRhDescriptorA           0x004c0548 /* Root Hub Descriptor A Register */
#define BCHP_USB_OHCI1_HcRhDescriptorB           0x004c054c /* Root Hub Descriptor B Register */
#define BCHP_USB_OHCI1_HcRhStatus                0x004c0550 /* Root Hub Status Register */
#define BCHP_USB_OHCI1_HcRhPortStatus1           0x004c0554 /* Root Hub Port Status Register for Port 1 */

#endif /* #ifndef BCHP_USB_OHCI1_H__ */

/* End of File */
