/***************************************************************************
 *     Copyright (c) 1999-2006, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 *
 * $brcm_Workfile: bchp_sun_top_ctrl.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 10/27/05 5:53p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Thu Oct 27 14:46:30 2005
 *                 MD5 Checksum         1facb4366229a2ae61df556fc4269540
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.006
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7400/rdb/a0/bchp_sun_top_ctrl.h $
 * 
 * Hydra_Software_Devel/1   10/27/05 5:53p jasonh
 * PR 17771: Initial version.
 *
 ***************************************************************************/

#ifndef BCHP_SUN_TOP_CTRL_H__
#define BCHP_SUN_TOP_CTRL_H__

/***************************************************************************
 *SUN_TOP_CTRL - Top Control registers
 ***************************************************************************/
#define BCHP_SUN_TOP_CTRL_PROD_REVISION          0x00404000 /* Product Revision ID */
#define BCHP_SUN_TOP_CTRL_SUN_REVISION           0x00404004 /* Sundry Revision ID */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL             0x00404008 /* Power-on reset control */
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY          0x0040400c /* Reset history */
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG             0x00404010 /* Serial Slave Port configuration register */
#define BCHP_SUN_TOP_CTRL_SW_RESET               0x00404014 /* Software reset register */
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL         0x00404018 /* Test port control */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE            0x0040401c /* Strapping values */
#define BCHP_SUN_TOP_CTRL_UNCLEARED_SCRATCH      0x00404020 /* Scratch register */
#define BCHP_SUN_TOP_CTRL_BOND_STATUS            0x00404024 /* Bond option value register */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST        0x00404028 /* OTP option test register */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS      0x0040402c /* OTP option status register */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_0            0x00404030 /* Semaphore channel 0 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_1            0x00404034 /* Semaphore channel 1 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_2            0x00404038 /* Semaphore channel 2 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_3            0x0040403c /* Semaphore channel 3 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_4            0x00404040 /* Semaphore channel 4 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_5            0x00404044 /* Semaphore channel 5 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_6            0x00404048 /* Semaphore channel 6 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_7            0x0040404c /* Semaphore channel 7 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_8            0x00404050 /* Semaphore channel 8 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_9            0x00404054 /* Semaphore channel 9 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_10           0x00404058 /* Semaphore channel 10 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_11           0x0040405c /* Semaphore channel 11 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_12           0x00404060 /* Semaphore channel 12 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_13           0x00404064 /* Semaphore channel 13 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_14           0x00404068 /* Semaphore channel 14 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_15           0x0040406c /* Semaphore channel 15 */
#define BCHP_SUN_TOP_CTRL_GEN_WATCHDOG_0         0x00404070 /* General watchdog timer 0 */
#define BCHP_SUN_TOP_CTRL_GEN_WATCHDOG_1         0x00404074 /* General watchdog timer 1 */
#define BCHP_SUN_TOP_CTRL_SATA_CTRL              0x00404078 /* Sata control register */
#define BCHP_SUN_TOP_CTRL_DAA_CTRL               0x0040407c /* DAA control register */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL          0x00404080 /* Simultaneous switching testmode control */
#define BCHP_SUN_TOP_CTRL_SPARE_CTRL             0x00404084 /* Spare control bits reserved for future use */
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN         0x00404088 /* EJTAG input bus enables */
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL       0x0040408c /* EJTAG output select */
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL      0x00404090 /* Block select for RO testmode */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0         0x00404094 /* Pin mux control register 0 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1         0x00404098 /* Pin mux control register 1 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2         0x0040409c /* Pin mux control register 2 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3         0x004040a0 /* Pin mux control register 3 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4         0x004040a4 /* Pin mux control register 4 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5         0x004040a8 /* Pin mux control register 5 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6         0x004040ac /* Pin mux control register 6 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7         0x004040b0 /* Pin mux control register 7 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8         0x004040b4 /* Pin mux control register 8 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9         0x004040b8 /* Pin mux control register 9 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10        0x004040bc /* Pin mux control register 10 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11        0x004040c0 /* Pin mux control register 11 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12        0x004040c4 /* Pin mux control register 12 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13        0x004040c8 /* Pin mux control register 13 */

/***************************************************************************
 *PROD_REVISION - Product Revision ID
 ***************************************************************************/
/* SUN_TOP_CTRL :: PROD_REVISION :: product_revision [31:00] */
#define BCHP_SUN_TOP_CTRL_PROD_REVISION_product_revision_MASK      0xffffffff
#define BCHP_SUN_TOP_CTRL_PROD_REVISION_product_revision_SHIFT     0

/***************************************************************************
 *SUN_REVISION - Sundry Revision ID
 ***************************************************************************/
/* SUN_TOP_CTRL :: SUN_REVISION :: reserved0 [31:16] */
#define BCHP_SUN_TOP_CTRL_SUN_REVISION_reserved0_MASK              0xffff0000
#define BCHP_SUN_TOP_CTRL_SUN_REVISION_reserved0_SHIFT             16

/* SUN_TOP_CTRL :: SUN_REVISION :: sundry_revision [15:00] */
#define BCHP_SUN_TOP_CTRL_SUN_REVISION_sundry_revision_MASK        0x0000ffff
#define BCHP_SUN_TOP_CTRL_SUN_REVISION_sundry_revision_SHIFT       0

/***************************************************************************
 *RESET_CTRL - Power-on reset control
 ***************************************************************************/
/* SUN_TOP_CTRL :: RESET_CTRL :: reserved0 [31:10] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_reserved0_MASK                0xfffffc00
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_reserved0_SHIFT               10

/* SUN_TOP_CTRL :: RESET_CTRL :: clear_reset_history [09:09] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_clear_reset_history_MASK      0x00000200
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_clear_reset_history_SHIFT     9

/* SUN_TOP_CTRL :: RESET_CTRL :: watchdog_reset_enable_lock [08:08] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_watchdog_reset_enable_lock_MASK 0x00000100
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_watchdog_reset_enable_lock_SHIFT 8

/* SUN_TOP_CTRL :: RESET_CTRL :: watchdog_reset_enable [07:07] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_watchdog_reset_enable_MASK    0x00000080
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_watchdog_reset_enable_SHIFT   7

/* SUN_TOP_CTRL :: RESET_CTRL :: front_panel_reset_enable_lock [06:06] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_front_panel_reset_enable_lock_MASK 0x00000040
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_front_panel_reset_enable_lock_SHIFT 6

/* SUN_TOP_CTRL :: RESET_CTRL :: front_panel_reset_enable [05:05] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_front_panel_reset_enable_MASK 0x00000020
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_front_panel_reset_enable_SHIFT 5

/* SUN_TOP_CTRL :: RESET_CTRL :: front_panel_reset_polarity [04:04] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_front_panel_reset_polarity_MASK 0x00000010
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_front_panel_reset_polarity_SHIFT 4

/* SUN_TOP_CTRL :: RESET_CTRL :: master_reset_en [03:03] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_master_reset_en_MASK          0x00000008
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_master_reset_en_SHIFT         3

/* SUN_TOP_CTRL :: RESET_CTRL :: sc_insert_reset_en [02:00] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_sc_insert_reset_en_MASK       0x00000007
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_sc_insert_reset_en_SHIFT      0

/***************************************************************************
 *RESET_HISTORY - Reset history
 ***************************************************************************/
/* SUN_TOP_CTRL :: RESET_HISTORY :: reserved0 [31:09] */
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_reserved0_MASK             0xfffffe00
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_reserved0_SHIFT            9

/* SUN_TOP_CTRL :: RESET_HISTORY :: cpu_chip_sft_sft_rst_b [08:08] */
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_cpu_chip_sft_sft_rst_b_MASK 0x00000100
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_cpu_chip_sft_sft_rst_b_SHIFT 8

/* SUN_TOP_CTRL :: RESET_HISTORY :: cpu_chip_hrd_sft_rst_b [07:07] */
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_cpu_chip_hrd_sft_rst_b_MASK 0x00000080
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_cpu_chip_hrd_sft_rst_b_SHIFT 7

/* SUN_TOP_CTRL :: RESET_HISTORY :: smartcard_insert_reset [06:06] */
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_smartcard_insert_reset_MASK 0x00000040
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_smartcard_insert_reset_SHIFT 6

/* SUN_TOP_CTRL :: RESET_HISTORY :: security_reset [05:05] */
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_security_reset_MASK        0x00000020
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_security_reset_SHIFT       5

/* SUN_TOP_CTRL :: RESET_HISTORY :: watchdog_timer_reset [04:04] */
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_watchdog_timer_reset_MASK  0x00000010
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_watchdog_timer_reset_SHIFT 4

/* SUN_TOP_CTRL :: RESET_HISTORY :: software_master_reset [03:03] */
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_software_master_reset_MASK 0x00000008
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_software_master_reset_SHIFT 3

/* SUN_TOP_CTRL :: RESET_HISTORY :: front_panel_4sec_reset [02:02] */
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_front_panel_4sec_reset_MASK 0x00000004
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_front_panel_4sec_reset_SHIFT 2

/* SUN_TOP_CTRL :: RESET_HISTORY :: main_chip_reset_input [01:01] */
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_main_chip_reset_input_MASK 0x00000002
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_main_chip_reset_input_SHIFT 1

/* SUN_TOP_CTRL :: RESET_HISTORY :: power_on_reset [00:00] */
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_power_on_reset_MASK        0x00000001
#define BCHP_SUN_TOP_CTRL_RESET_HISTORY_power_on_reset_SHIFT       0

/***************************************************************************
 *SSP_CONFIG - Serial Slave Port configuration register
 ***************************************************************************/
/* SUN_TOP_CTRL :: SSP_CONFIG :: reserved0 [31:11] */
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_reserved0_MASK                0xfffff800
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_reserved0_SHIFT               11

/* SUN_TOP_CTRL :: SSP_CONFIG :: serial_adr_cfg [10:07] */
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_serial_adr_cfg_MASK           0x00000780
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_serial_adr_cfg_SHIFT          7

/* SUN_TOP_CTRL :: SSP_CONFIG :: probe_mux_sel [06:03] */
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_probe_mux_sel_MASK            0x00000078
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_probe_mux_sel_SHIFT           3

/* SUN_TOP_CTRL :: SSP_CONFIG :: dly_disable [02:02] */
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_dly_disable_MASK              0x00000004
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_dly_disable_SHIFT             2

/* SUN_TOP_CTRL :: SSP_CONFIG :: spi_mode [01:01] */
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_spi_mode_MASK                 0x00000002
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_spi_mode_SHIFT                1

/* SUN_TOP_CTRL :: SSP_CONFIG :: ssp_module_enable [00:00] */
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_ssp_module_enable_MASK        0x00000001
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_ssp_module_enable_SHIFT       0

/***************************************************************************
 *SW_RESET - Software reset register
 ***************************************************************************/
/* SUN_TOP_CTRL :: SW_RESET :: chip_master_reset [31:31] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_chip_master_reset_MASK          0x80000000
#define BCHP_SUN_TOP_CTRL_SW_RESET_chip_master_reset_SHIFT         31

/* SUN_TOP_CTRL :: SW_RESET :: cpu_sw_reset_1shot [30:30] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_cpu_sw_reset_1shot_MASK         0x40000000
#define BCHP_SUN_TOP_CTRL_SW_RESET_cpu_sw_reset_1shot_SHIFT        30

/* SUN_TOP_CTRL :: SW_RESET :: ext_sys_reset_1shot [29:29] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_ext_sys_reset_1shot_MASK        0x20000000
#define BCHP_SUN_TOP_CTRL_SW_RESET_ext_sys_reset_1shot_SHIFT       29

/* SUN_TOP_CTRL :: SW_RESET :: reserved0 [28:28] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved0_MASK                  0x10000000
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved0_SHIFT                 28

/* SUN_TOP_CTRL :: SW_RESET :: mc16_sw_reset [27:27] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_mc16_sw_reset_MASK              0x08000000
#define BCHP_SUN_TOP_CTRL_SW_RESET_mc16_sw_reset_SHIFT             27

/* SUN_TOP_CTRL :: SW_RESET :: avd1_sw_reset [26:26] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_avd1_sw_reset_MASK              0x04000000
#define BCHP_SUN_TOP_CTRL_SW_RESET_avd1_sw_reset_SHIFT             26

/* SUN_TOP_CTRL :: SW_RESET :: avd0_sw_reset [25:25] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_avd0_sw_reset_MASK              0x02000000
#define BCHP_SUN_TOP_CTRL_SW_RESET_avd0_sw_reset_SHIFT             25

/* SUN_TOP_CTRL :: SW_RESET :: aio_sw_reset [24:24] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_aio_sw_reset_MASK               0x01000000
#define BCHP_SUN_TOP_CTRL_SW_RESET_aio_sw_reset_SHIFT              24

/* SUN_TOP_CTRL :: SW_RESET :: rptd_sw_reset [23:23] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_rptd_sw_reset_MASK              0x00800000
#define BCHP_SUN_TOP_CTRL_SW_RESET_rptd_sw_reset_SHIFT             23

/* SUN_TOP_CTRL :: SW_RESET :: bvnm_sw_reset [22:22] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_bvnm_sw_reset_MASK              0x00400000
#define BCHP_SUN_TOP_CTRL_SW_RESET_bvnm_sw_reset_SHIFT             22

/* SUN_TOP_CTRL :: SW_RESET :: ext_sys_reset_level [21:21] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_ext_sys_reset_level_MASK        0x00200000
#define BCHP_SUN_TOP_CTRL_SW_RESET_ext_sys_reset_level_SHIFT       21

/* SUN_TOP_CTRL :: SW_RESET :: usb_sw_reset [20:20] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_usb_sw_reset_MASK               0x00100000
#define BCHP_SUN_TOP_CTRL_SW_RESET_usb_sw_reset_SHIFT              20

/* SUN_TOP_CTRL :: SW_RESET :: reserved1 [19:19] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved1_MASK                  0x00080000
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved1_SHIFT                 19

/* SUN_TOP_CTRL :: SW_RESET :: sata_sw_reset [18:18] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_sata_sw_reset_MASK              0x00040000
#define BCHP_SUN_TOP_CTRL_SW_RESET_sata_sw_reset_SHIFT             18

/* SUN_TOP_CTRL :: SW_RESET :: reserved2 [17:17] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved2_MASK                  0x00020000
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved2_SHIFT                 17

/* SUN_TOP_CTRL :: SW_RESET :: gfx_sw_reset [16:16] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_gfx_sw_reset_MASK               0x00010000
#define BCHP_SUN_TOP_CTRL_SW_RESET_gfx_sw_reset_SHIFT              16

/* SUN_TOP_CTRL :: SW_RESET :: reserved3 [15:14] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved3_MASK                  0x0000c000
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved3_SHIFT                 14

/* SUN_TOP_CTRL :: SW_RESET :: xpt_sw_reset [13:13] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_xpt_sw_reset_MASK               0x00002000
#define BCHP_SUN_TOP_CTRL_SW_RESET_xpt_sw_reset_SHIFT              13

/* SUN_TOP_CTRL :: SW_RESET :: reserved4 [12:12] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved4_MASK                  0x00001000
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved4_SHIFT                 12

/* SUN_TOP_CTRL :: SW_RESET :: vec_sw_reset [11:11] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_vec_sw_reset_MASK               0x00000800
#define BCHP_SUN_TOP_CTRL_SW_RESET_vec_sw_reset_SHIFT              11

/* SUN_TOP_CTRL :: SW_RESET :: reserved5 [10:10] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved5_MASK                  0x00000400
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved5_SHIFT                 10

/* SUN_TOP_CTRL :: SW_RESET :: hdmi_sw_reset [09:09] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_hdmi_sw_reset_MASK              0x00000200
#define BCHP_SUN_TOP_CTRL_SW_RESET_hdmi_sw_reset_SHIFT             9

/* SUN_TOP_CTRL :: SW_RESET :: bvnb_sw_reset [08:08] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_bvnb_sw_reset_MASK              0x00000100
#define BCHP_SUN_TOP_CTRL_SW_RESET_bvnb_sw_reset_SHIFT             8

/* SUN_TOP_CTRL :: SW_RESET :: bvnf_sw_reset [07:07] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_bvnf_sw_reset_MASK              0x00000080
#define BCHP_SUN_TOP_CTRL_SW_RESET_bvnf_sw_reset_SHIFT             7

/* SUN_TOP_CTRL :: SW_RESET :: rfm_sw_reset [06:06] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_rfm_sw_reset_MASK               0x00000040
#define BCHP_SUN_TOP_CTRL_SW_RESET_rfm_sw_reset_SHIFT              6

/* SUN_TOP_CTRL :: SW_RESET :: reserved6 [05:05] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved6_MASK                  0x00000020
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved6_SHIFT                 5

/* SUN_TOP_CTRL :: SW_RESET :: enet_sw_reset [04:04] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_enet_sw_reset_MASK              0x00000010
#define BCHP_SUN_TOP_CTRL_SW_RESET_enet_sw_reset_SHIFT             4

/* SUN_TOP_CTRL :: SW_RESET :: cpu_sw_reset_level [03:03] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_cpu_sw_reset_level_MASK         0x00000008
#define BCHP_SUN_TOP_CTRL_SW_RESET_cpu_sw_reset_level_SHIFT        3

/* SUN_TOP_CTRL :: SW_RESET :: ebi_sw_reset [02:02] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_ebi_sw_reset_MASK               0x00000004
#define BCHP_SUN_TOP_CTRL_SW_RESET_ebi_sw_reset_SHIFT              2

/* SUN_TOP_CTRL :: SW_RESET :: pci_sw_reset [01:01] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_pci_sw_reset_MASK               0x00000002
#define BCHP_SUN_TOP_CTRL_SW_RESET_pci_sw_reset_SHIFT              1

/* SUN_TOP_CTRL :: SW_RESET :: sundry_sw_reset [00:00] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_sundry_sw_reset_MASK            0x00000001
#define BCHP_SUN_TOP_CTRL_SW_RESET_sundry_sw_reset_SHIFT           0

/***************************************************************************
 *TEST_PORT_CTRL - Test port control
 ***************************************************************************/
/* SUN_TOP_CTRL :: TEST_PORT_CTRL :: sundry_local_tp_out_sel [31:30] */
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_sundry_local_tp_out_sel_MASK 0xc0000000
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_sundry_local_tp_out_sel_SHIFT 30
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_sundry_local_tp_out_sel_SEMAPHORE_0 0
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_sundry_local_tp_out_sel_SEMAPHORE_1 1
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_sundry_local_tp_out_sel_SMART_MODEM 2
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_sundry_local_tp_out_sel_DAA 3

/* SUN_TOP_CTRL :: TEST_PORT_CTRL :: reserved0 [29:07] */
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_reserved0_MASK            0x3fffff80
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_reserved0_SHIFT           7

/* SUN_TOP_CTRL :: TEST_PORT_CTRL :: tp_select [06:05] */
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_tp_select_MASK            0x00000060
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_tp_select_SHIFT           5

/* SUN_TOP_CTRL :: TEST_PORT_CTRL :: encoded_tp_enable [04:00] */
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_MASK    0x0000001f
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_SHIFT   0
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_ENET    0
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_CPU     1
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_RFM     2
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_SATA    3
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_BVNM    4
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_BVNB    5
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_HDMI    6
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_VEC     8
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_GFX     14
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_HIF     15
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_USB     16
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_SUN     17
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_BVNF    19
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_XPT     21
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_RPTD    22
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_AIO     23
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_AVD0    24
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_BSP     25
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_MC16    26
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_AVD1    27

/***************************************************************************
 *STRAP_VALUE - Strapping values
 ***************************************************************************/
/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_ddr2_present [31:31] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ddr2_present_MASK      0x80000000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ddr2_present_SHIFT     31

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_reset_outb_def_val [30:30] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_reset_outb_def_val_MASK 0x40000000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_reset_outb_def_val_SHIFT 30

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_test_debug_en [29:28] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_test_debug_en_MASK     0x30000000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_test_debug_en_SHIFT    28

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_nmi_polarity [27:27] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_nmi_polarity_MASK      0x08000000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_nmi_polarity_SHIFT     27

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_sel_33_27_mhz_clock [26:26] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_sel_33_27_mhz_clock_MASK 0x04000000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_sel_33_27_mhz_clock_SHIFT 26

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_spare_1 [25:25] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_spare_1_MASK           0x02000000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_spare_1_SHIFT          25

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_spare_0 [24:24] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_spare_0_MASK           0x01000000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_spare_0_SHIFT          24

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_xtal_adj [23:20] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_xtal_adj_MASK          0x00f00000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_xtal_adj_SHIFT         20

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_ebi_rom_size [19:18] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ebi_rom_size_MASK      0x000c0000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ebi_rom_size_SHIFT     18

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_ebi_invert_addr [17:17] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ebi_invert_addr_MASK   0x00020000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ebi_invert_addr_SHIFT  17

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_ebi_boot_memory [16:16] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ebi_boot_memory_MASK   0x00010000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ebi_boot_memory_SHIFT  16

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_ddr_configuration [15:12] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ddr_configuration_MASK 0x0000f000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ddr_configuration_SHIFT 12

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_system_big_endian [11:11] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_system_big_endian_MASK 0x00000800
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_system_big_endian_SHIFT 11

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_ebi_cs_swap [10:10] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ebi_cs_swap_MASK       0x00000400
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ebi_cs_swap_SHIFT      10

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_spi_slave_enable [09:09] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_spi_slave_enable_MASK  0x00000200
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_spi_slave_enable_SHIFT 9

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_pci_memwin_size [08:07] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_pci_memwin_size_MASK   0x00000180
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_pci_memwin_size_SHIFT  7

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_pci_memwin2_en [06:06] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_pci_memwin2_en_MASK    0x00000040
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_pci_memwin2_en_SHIFT   6

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_pci_memwin1_en [05:05] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_pci_memwin1_en_MASK    0x00000020
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_pci_memwin1_en_SHIFT   5

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_pci_client [04:04] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_pci_client_MASK        0x00000010
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_pci_client_SHIFT       4

/* SUN_TOP_CTRL :: STRAP_VALUE :: reserved0 [03:02] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_reserved0_MASK               0x0000000c
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_reserved0_SHIFT              2

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_nand_flash [01:01] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_nand_flash_MASK        0x00000002
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_nand_flash_SHIFT       1

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_reset_ext_mode [00:00] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_reset_ext_mode_MASK    0x00000001
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_reset_ext_mode_SHIFT   0

/***************************************************************************
 *UNCLEARED_SCRATCH - Scratch register
 ***************************************************************************/
/* SUN_TOP_CTRL :: UNCLEARED_SCRATCH :: uncleared_scratch [31:00] */
#define BCHP_SUN_TOP_CTRL_UNCLEARED_SCRATCH_uncleared_scratch_MASK 0xffffffff
#define BCHP_SUN_TOP_CTRL_UNCLEARED_SCRATCH_uncleared_scratch_SHIFT 0

/***************************************************************************
 *BOND_STATUS - Bond option value register
 ***************************************************************************/
/* SUN_TOP_CTRL :: BOND_STATUS :: reserved0 [31:01] */
#define BCHP_SUN_TOP_CTRL_BOND_STATUS_reserved0_MASK               0xfffffffe
#define BCHP_SUN_TOP_CTRL_BOND_STATUS_reserved0_SHIFT              1

/* SUN_TOP_CTRL :: BOND_STATUS :: bond_reserved [00:00] */
#define BCHP_SUN_TOP_CTRL_BOND_STATUS_bond_reserved_MASK           0x00000001
#define BCHP_SUN_TOP_CTRL_BOND_STATUS_bond_reserved_SHIFT          0

/***************************************************************************
 *OTP_OPTION_TEST - OTP option test register
 ***************************************************************************/
/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: reserved0 [31:18] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_reserved0_MASK           0xfffc0000
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_reserved0_SHIFT          18

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_spare [17:14] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_spare_MASK    0x0003c000
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_spare_SHIFT   14

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_sata_disable [13:13] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_sata_disable_MASK 0x00002000
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_sata_disable_SHIFT 13

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_avc1_disable [12:12] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_avc1_disable_MASK 0x00001000
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_avc1_disable_SHIFT 12

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_en_i2c [11:11] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_en_i2c_MASK   0x00000800
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_en_i2c_SHIFT  11

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_en_pci_ebi [10:10] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_en_pci_ebi_MASK 0x00000400
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_en_pci_ebi_SHIFT 10

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_en_testport [09:09] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_en_testport_MASK 0x00000200
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_en_testport_SHIFT 9

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_en_jtag [08:08] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_en_jtag_MASK  0x00000100
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_en_jtag_SHIFT 8

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_ebi_cs_swap_ovrd [07:07] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_ebi_cs_swap_ovrd_MASK 0x00000080
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_ebi_cs_swap_ovrd_SHIFT 7

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_int_daa_disable [06:06] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_int_daa_disable_MASK 0x00000040
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_int_daa_disable_SHIFT 6

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_hdcp_disable [05:05] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_hdcp_disable_MASK 0x00000020
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_hdcp_disable_SHIFT 5

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_macrovision_disable [04:04] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_macrovision_disable_MASK 0x00000010
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_macrovision_disable_SHIFT 4

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_product_id [03:00] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_product_id_MASK 0x0000000f
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_product_id_SHIFT 0

/***************************************************************************
 *OTP_OPTION_STATUS - OTP option status register
 ***************************************************************************/
/* SUN_TOP_CTRL :: OTP_OPTION_STATUS :: reserved0 [31:18] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_reserved0_MASK         0xfffc0000
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_reserved0_SHIFT        18

/* SUN_TOP_CTRL :: OTP_OPTION_STATUS :: otp_option_spare [17:14] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_spare_MASK  0x0003c000
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_spare_SHIFT 14

/* SUN_TOP_CTRL :: OTP_OPTION_STATUS :: otp_option_sata_disable [13:13] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_sata_disable_MASK 0x00002000
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_sata_disable_SHIFT 13

/* SUN_TOP_CTRL :: OTP_OPTION_STATUS :: otp_option_avc1_disable [12:12] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_avc1_disable_MASK 0x00001000
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_avc1_disable_SHIFT 12

/* SUN_TOP_CTRL :: OTP_OPTION_STATUS :: otp_option_en_i2c [11:11] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_en_i2c_MASK 0x00000800
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_en_i2c_SHIFT 11

/* SUN_TOP_CTRL :: OTP_OPTION_STATUS :: otp_option_en_pci_ebi [10:10] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_en_pci_ebi_MASK 0x00000400
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_en_pci_ebi_SHIFT 10

/* SUN_TOP_CTRL :: OTP_OPTION_STATUS :: otp_option_en_testport [09:09] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_en_testport_MASK 0x00000200
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_en_testport_SHIFT 9

/* SUN_TOP_CTRL :: OTP_OPTION_STATUS :: otp_option_en_jtag [08:08] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_en_jtag_MASK 0x00000100
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_en_jtag_SHIFT 8

/* SUN_TOP_CTRL :: OTP_OPTION_STATUS :: otp_option_ebi_cs_swap_ovrd [07:07] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_ebi_cs_swap_ovrd_MASK 0x00000080
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_ebi_cs_swap_ovrd_SHIFT 7

/* SUN_TOP_CTRL :: OTP_OPTION_STATUS :: otp_option_int_daa_disable [06:06] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_int_daa_disable_MASK 0x00000040
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_int_daa_disable_SHIFT 6

/* SUN_TOP_CTRL :: OTP_OPTION_STATUS :: otp_option_hdcp_disable [05:05] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_hdcp_disable_MASK 0x00000020
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_hdcp_disable_SHIFT 5

/* SUN_TOP_CTRL :: OTP_OPTION_STATUS :: otp_option_macrovision_disable [04:04] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_macrovision_disable_MASK 0x00000010
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_macrovision_disable_SHIFT 4

/* SUN_TOP_CTRL :: OTP_OPTION_STATUS :: otp_option_product_id [03:00] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_product_id_MASK 0x0000000f
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_STATUS_otp_option_product_id_SHIFT 0

/***************************************************************************
 *SEMAPHORE_0 - Semaphore channel 0
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_0 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_0_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_0_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_0 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_0_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_0_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_1 - Semaphore channel 1
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_1 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_1_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_1_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_1 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_1_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_1_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_2 - Semaphore channel 2
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_2 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_2_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_2_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_2 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_2_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_2_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_3 - Semaphore channel 3
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_3 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_3_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_3_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_3 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_3_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_3_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_4 - Semaphore channel 4
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_4 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_4_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_4_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_4 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_4_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_4_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_5 - Semaphore channel 5
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_5 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_5_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_5_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_5 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_5_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_5_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_6 - Semaphore channel 6
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_6 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_6_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_6_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_6 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_6_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_6_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_7 - Semaphore channel 7
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_7 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_7_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_7_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_7 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_7_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_7_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_8 - Semaphore channel 8
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_8 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_8_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_8_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_8 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_8_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_8_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_9 - Semaphore channel 9
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_9 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_9_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_9_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_9 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_9_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_9_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_10 - Semaphore channel 10
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_10 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_10_reserved0_MASK              0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_10_reserved0_SHIFT             8

/* SUN_TOP_CTRL :: SEMAPHORE_10 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_10_semaphore_ctrl_MASK         0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_10_semaphore_ctrl_SHIFT        0

/***************************************************************************
 *SEMAPHORE_11 - Semaphore channel 11
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_11 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_11_reserved0_MASK              0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_11_reserved0_SHIFT             8

/* SUN_TOP_CTRL :: SEMAPHORE_11 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_11_semaphore_ctrl_MASK         0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_11_semaphore_ctrl_SHIFT        0

/***************************************************************************
 *SEMAPHORE_12 - Semaphore channel 12
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_12 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_12_reserved0_MASK              0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_12_reserved0_SHIFT             8

/* SUN_TOP_CTRL :: SEMAPHORE_12 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_12_semaphore_ctrl_MASK         0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_12_semaphore_ctrl_SHIFT        0

/***************************************************************************
 *SEMAPHORE_13 - Semaphore channel 13
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_13 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_13_reserved0_MASK              0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_13_reserved0_SHIFT             8

/* SUN_TOP_CTRL :: SEMAPHORE_13 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_13_semaphore_ctrl_MASK         0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_13_semaphore_ctrl_SHIFT        0

/***************************************************************************
 *SEMAPHORE_14 - Semaphore channel 14
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_14 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_14_reserved0_MASK              0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_14_reserved0_SHIFT             8

/* SUN_TOP_CTRL :: SEMAPHORE_14 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_14_semaphore_ctrl_MASK         0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_14_semaphore_ctrl_SHIFT        0

/***************************************************************************
 *SEMAPHORE_15 - Semaphore channel 15
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_15 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_15_reserved0_MASK              0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_15_reserved0_SHIFT             8

/* SUN_TOP_CTRL :: SEMAPHORE_15 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_15_semaphore_ctrl_MASK         0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_15_semaphore_ctrl_SHIFT        0

/***************************************************************************
 *GEN_WATCHDOG_0 - General watchdog timer 0
 ***************************************************************************/
/* SUN_TOP_CTRL :: GEN_WATCHDOG_0 :: watchdog_timeout_value [31:00] */
#define BCHP_SUN_TOP_CTRL_GEN_WATCHDOG_0_watchdog_timeout_value_MASK 0xffffffff
#define BCHP_SUN_TOP_CTRL_GEN_WATCHDOG_0_watchdog_timeout_value_SHIFT 0

/***************************************************************************
 *GEN_WATCHDOG_1 - General watchdog timer 1
 ***************************************************************************/
/* SUN_TOP_CTRL :: GEN_WATCHDOG_1 :: watchdog_timeout_value [31:00] */
#define BCHP_SUN_TOP_CTRL_GEN_WATCHDOG_1_watchdog_timeout_value_MASK 0xffffffff
#define BCHP_SUN_TOP_CTRL_GEN_WATCHDOG_1_watchdog_timeout_value_SHIFT 0

/***************************************************************************
 *SATA_CTRL - Sata control register
 ***************************************************************************/
/* SUN_TOP_CTRL :: SATA_CTRL :: reserved0 [31:03] */
#define BCHP_SUN_TOP_CTRL_SATA_CTRL_reserved0_MASK                 0xfffffff8
#define BCHP_SUN_TOP_CTRL_SATA_CTRL_reserved0_SHIFT                3

/* SUN_TOP_CTRL :: SATA_CTRL :: sata_sscen [02:02] */
#define BCHP_SUN_TOP_CTRL_SATA_CTRL_sata_sscen_MASK                0x00000004
#define BCHP_SUN_TOP_CTRL_SATA_CTRL_sata_sscen_SHIFT               2

/* SUN_TOP_CTRL :: SATA_CTRL :: sata_ana_xtaliddq [01:01] */
#define BCHP_SUN_TOP_CTRL_SATA_CTRL_sata_ana_xtaliddq_MASK         0x00000002
#define BCHP_SUN_TOP_CTRL_SATA_CTRL_sata_ana_xtaliddq_SHIFT        1

/* SUN_TOP_CTRL :: SATA_CTRL :: sata_ana_pwrdn [00:00] */
#define BCHP_SUN_TOP_CTRL_SATA_CTRL_sata_ana_pwrdn_MASK            0x00000001
#define BCHP_SUN_TOP_CTRL_SATA_CTRL_sata_ana_pwrdn_SHIFT           0

/***************************************************************************
 *DAA_CTRL - DAA control register
 ***************************************************************************/
/* SUN_TOP_CTRL :: DAA_CTRL :: reserved0 [31:02] */
#define BCHP_SUN_TOP_CTRL_DAA_CTRL_reserved0_MASK                  0xfffffffc
#define BCHP_SUN_TOP_CTRL_DAA_CTRL_reserved0_SHIFT                 2

/* SUN_TOP_CTRL :: DAA_CTRL :: daa_iddq [01:01] */
#define BCHP_SUN_TOP_CTRL_DAA_CTRL_daa_iddq_MASK                   0x00000002
#define BCHP_SUN_TOP_CTRL_DAA_CTRL_daa_iddq_SHIFT                  1

/* SUN_TOP_CTRL :: DAA_CTRL :: daa_bypass [00:00] */
#define BCHP_SUN_TOP_CTRL_DAA_CTRL_daa_bypass_MASK                 0x00000001
#define BCHP_SUN_TOP_CTRL_DAA_CTRL_daa_bypass_SHIFT                0

/***************************************************************************
 *SS_TMODE_CTRL - Simultaneous switching testmode control
 ***************************************************************************/
/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: reserved0 [31:22] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_reserved0_MASK             0xffc00000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_reserved0_SHIFT            22

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: mc2_ss_tmode_en [21:21] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_mc2_ss_tmode_en_MASK       0x00200000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_mc2_ss_tmode_en_SHIFT      21

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: mc1_ss_tmode_en [20:20] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_mc1_ss_tmode_en_MASK       0x00100000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_mc1_ss_tmode_en_SHIFT      20

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: avd1_ss_tmode_en [19:19] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_avd1_ss_tmode_en_MASK      0x00080000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_avd1_ss_tmode_en_SHIFT     19

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: bsp_ss_tmode_en [18:18] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_bsp_ss_tmode_en_MASK       0x00040000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_bsp_ss_tmode_en_SHIFT      18

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: avd0_ss_tmode_en [17:17] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_avd0_ss_tmode_en_MASK      0x00020000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_avd0_ss_tmode_en_SHIFT     17

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: aio_ss_tmode_en [16:16] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_aio_ss_tmode_en_MASK       0x00010000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_aio_ss_tmode_en_SHIFT      16

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: rptd_ss_tmode_en [15:15] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_rptd_ss_tmode_en_MASK      0x00008000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_rptd_ss_tmode_en_SHIFT     15

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: sata_ss_tmode_en [14:14] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_sata_ss_tmode_en_MASK      0x00004000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_sata_ss_tmode_en_SHIFT     14

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: xpt_ss_tmode_en [13:13] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_xpt_ss_tmode_en_MASK       0x00002000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_xpt_ss_tmode_en_SHIFT      13

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: enet_ss_tmode_en [12:12] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_enet_ss_tmode_en_MASK      0x00001000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_enet_ss_tmode_en_SHIFT     12

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: reserved1 [11:08] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_reserved1_MASK             0x00000f00
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_reserved1_SHIFT            8

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: gfx_ss_tmode_en [07:07] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_gfx_ss_tmode_en_MASK       0x00000080
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_gfx_ss_tmode_en_SHIFT      7

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: sun_ss_tmode_en [06:06] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_sun_ss_tmode_en_MASK       0x00000040
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_sun_ss_tmode_en_SHIFT      6

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: reserved2 [05:05] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_reserved2_MASK             0x00000020
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_reserved2_SHIFT            5

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: usb_ss_tmode_en [04:04] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_usb_ss_tmode_en_MASK       0x00000010
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_usb_ss_tmode_en_SHIFT      4

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: hif_ss_tmode_en [03:03] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_hif_ss_tmode_en_MASK       0x00000008
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_hif_ss_tmode_en_SHIFT      3

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: bvnm_ss_tmode_en [02:02] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_bvnm_ss_tmode_en_MASK      0x00000004
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_bvnm_ss_tmode_en_SHIFT     2

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: bvnb_ss_tmode_en [01:01] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_bvnb_ss_tmode_en_MASK      0x00000002
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_bvnb_ss_tmode_en_SHIFT     1

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: bvnf_ss_tmode_en [00:00] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_bvnf_ss_tmode_en_MASK      0x00000001
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_bvnf_ss_tmode_en_SHIFT     0

/***************************************************************************
 *SPARE_CTRL - Spare control bits reserved for future use
 ***************************************************************************/
/* SUN_TOP_CTRL :: SPARE_CTRL :: spare_ctrl [31:00] */
#define BCHP_SUN_TOP_CTRL_SPARE_CTRL_spare_ctrl_MASK               0xffffffff
#define BCHP_SUN_TOP_CTRL_SPARE_CTRL_spare_ctrl_SHIFT              0

/***************************************************************************
 *EJTAG_INPUT_EN - EJTAG input bus enables
 ***************************************************************************/
/* SUN_TOP_CTRL :: EJTAG_INPUT_EN :: reserved0 [31:07] */
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_reserved0_MASK            0xffffff80
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_reserved0_SHIFT           7

/* SUN_TOP_CTRL :: EJTAG_INPUT_EN :: ejtag_input_enable [06:00] */
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_ejtag_input_enable_MASK   0x0000007f
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_ejtag_input_enable_SHIFT  0
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_ejtag_input_enable_NOT_USED_CPU_ONE_HOT 1
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_ejtag_input_enable_MAIN_MIPS_CPU_ONE_HOT 2
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_ejtag_input_enable_AUDIO_ZSP_CPU_ONE_HOT 4
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_ejtag_input_enable_AVD0_OL_CPU_ONE_HOT 8
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_ejtag_input_enable_AVD0_IL_CPU_ONE_HOT 16
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_ejtag_input_enable_AVD1_OL_CPU_ONE_HOT 32
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_ejtag_input_enable_AVD1_IL_CPU_ONE_HOT 64

/***************************************************************************
 *EJTAG_OUTPUT_SEL - EJTAG output select
 ***************************************************************************/
/* SUN_TOP_CTRL :: EJTAG_OUTPUT_SEL :: reserved0 [31:03] */
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_reserved0_MASK          0xfffffff8
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_reserved0_SHIFT         3

/* SUN_TOP_CTRL :: EJTAG_OUTPUT_SEL :: ejtag_output_sel [02:00] */
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_ejtag_output_sel_MASK   0x00000007
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_ejtag_output_sel_SHIFT  0
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_ejtag_output_sel_NOT_USED_CPU 0
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_ejtag_output_sel_MAIN_MIPS_CPU 1
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_ejtag_output_sel_AUDIO_ZSP_CPU 2
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_ejtag_output_sel_AVD0_OL_CPU 3
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_ejtag_output_sel_AVD0_IL_CPU 4
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_ejtag_output_sel_AVD1_OL_CPU 5
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_ejtag_output_sel_AVD1_IL_CPU 6

/***************************************************************************
 *RO_TEST_BLOCK_SEL - Block select for RO testmode
 ***************************************************************************/
/* SUN_TOP_CTRL :: RO_TEST_BLOCK_SEL :: reserved0 [31:03] */
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_reserved0_MASK         0xfffffff8
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_reserved0_SHIFT        3

/* SUN_TOP_CTRL :: RO_TEST_BLOCK_SEL :: ro_test_block_select [02:00] */
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_MASK 0x00000007
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_SHIFT 0
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_NOT_USED_RO_TEST_ID 0
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_IOBUF_0_RO_TEST_ID 1
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_IOBUF_1_RO_TEST_ID 2
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_XPT_RO_TEST_ID 3
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_SUN_RO_TEST_ID 4
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_AVD1_RO_TEST_ID 5
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_VEC_RO_TEST_ID 6
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_RPTD_RO_TEST_ID 7

/***************************************************************************
 *PIN_MUX_CTRL_0 - Pin mux control register 0
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: pci_ad03 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pci_ad03_MASK             0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pci_ad03_SHIFT            30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: pci_ad02 [29:28] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pci_ad02_MASK             0x30000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pci_ad02_SHIFT            28

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: pci_ad01 [27:26] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pci_ad01_MASK             0x0c000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pci_ad01_SHIFT            26

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: pci_ad00 [25:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pci_ad00_MASK             0x03000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pci_ad00_SHIFT            24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: vo0_656_clk [23:22] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_clk_MASK          0x00c00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_clk_SHIFT         22

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: vo0_656_7 [21:20] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_7_MASK            0x00300000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_7_SHIFT           20

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: vo0_656_6 [19:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_6_MASK            0x000c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_6_SHIFT           18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: vo0_656_5 [17:16] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_5_MASK            0x00030000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_5_SHIFT           16

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: vo0_656_4 [15:14] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_4_MASK            0x0000c000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_4_SHIFT           14

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: vo0_656_3 [13:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_3_MASK            0x00003000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_3_SHIFT           12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: vo0_656_2 [11:10] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_2_MASK            0x00000c00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_2_SHIFT           10

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: vo0_656_1 [09:08] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_1_MASK            0x00000300
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_1_SHIFT           8

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: vo0_656_0 [07:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_0_MASK            0x000000c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_vo0_656_0_SHIFT           6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: rmx_sync0 [05:04] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_sync0_MASK            0x00000030
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_sync0_SHIFT           4

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: rmx_data0 [03:02] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_data0_MASK            0x0000000c
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_data0_SHIFT           2

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: rmx_clk0 [01:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_clk0_MASK             0x00000003
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_clk0_SHIFT            0

/***************************************************************************
 *PIN_MUX_CTRL_1 - Pin mux control register 1
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: pci_ad19 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad19_MASK             0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad19_SHIFT            30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: pci_ad18 [29:28] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad18_MASK             0x30000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad18_SHIFT            28

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: pci_ad17 [27:26] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad17_MASK             0x0c000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad17_SHIFT            26

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: pci_ad16 [25:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad16_MASK             0x03000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad16_SHIFT            24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: pci_ad15 [23:22] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad15_MASK             0x00c00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad15_SHIFT            22

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: pci_ad14 [21:20] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad14_MASK             0x00300000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad14_SHIFT            20

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: pci_ad13 [19:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad13_MASK             0x000c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad13_SHIFT            18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: pci_ad12 [17:16] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad12_MASK             0x00030000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad12_SHIFT            16

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: pci_ad11 [15:14] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad11_MASK             0x0000c000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad11_SHIFT            14

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: pci_ad10 [13:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad10_MASK             0x00003000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad10_SHIFT            12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: pci_ad09 [11:10] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad09_MASK             0x00000c00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad09_SHIFT            10

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: pci_ad08 [09:08] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad08_MASK             0x00000300
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad08_SHIFT            8

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: pci_ad07 [07:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad07_MASK             0x000000c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad07_SHIFT            6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: pci_ad06 [05:04] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad06_MASK             0x00000030
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad06_SHIFT            4

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: pci_ad05 [03:02] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad05_MASK             0x0000000c
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad05_SHIFT            2

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: pci_ad04 [01:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad04_MASK             0x00000003
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_pci_ad04_SHIFT            0

/***************************************************************************
 *PIN_MUX_CTRL_2 - Pin mux control register 2
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: reserved0 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_reserved0_MASK            0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_reserved0_SHIFT           30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: gpio_001 [29:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_001_MASK             0x38000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_001_SHIFT            27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: gpio_000 [26:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_000_MASK             0x07000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_gpio_000_SHIFT            24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: pci_ad31 [23:22] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad31_MASK             0x00c00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad31_SHIFT            22

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: pci_ad30 [21:20] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad30_MASK             0x00300000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad30_SHIFT            20

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: pci_ad29 [19:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad29_MASK             0x000c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad29_SHIFT            18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: pci_ad28 [17:16] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad28_MASK             0x00030000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad28_SHIFT            16

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: pci_ad27 [15:14] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad27_MASK             0x0000c000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad27_SHIFT            14

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: pci_ad26 [13:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad26_MASK             0x00003000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad26_SHIFT            12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: pci_ad25 [11:10] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad25_MASK             0x00000c00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad25_SHIFT            10

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: pci_ad24 [09:08] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad24_MASK             0x00000300
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad24_SHIFT            8

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: pci_ad23 [07:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad23_MASK             0x000000c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad23_SHIFT            6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: pci_ad22 [05:04] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad22_MASK             0x00000030
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad22_SHIFT            4

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: pci_ad21 [03:02] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad21_MASK             0x0000000c
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad21_SHIFT            2

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: pci_ad20 [01:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad20_MASK             0x00000003
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_pci_ad20_SHIFT            0

/***************************************************************************
 *PIN_MUX_CTRL_3 - Pin mux control register 3
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: reserved0 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_reserved0_MASK            0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_reserved0_SHIFT           30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: gpio_011 [29:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_011_MASK             0x38000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_011_SHIFT            27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: gpio_010 [26:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_010_MASK             0x07000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_010_SHIFT            24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: gpio_009 [23:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_009_MASK             0x00e00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_009_SHIFT            21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: gpio_008 [20:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_008_MASK             0x001c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_008_SHIFT            18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: gpio_007 [17:15] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_007_MASK             0x00038000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_007_SHIFT            15

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: gpio_006 [14:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_006_MASK             0x00007000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_006_SHIFT            12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: gpio_005 [11:09] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_005_MASK             0x00000e00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_005_SHIFT            9

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: gpio_004 [08:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_004_MASK             0x000001c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_004_SHIFT            6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: gpio_003 [05:03] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_003_MASK             0x00000038
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_003_SHIFT            3

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: gpio_002 [02:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_002_MASK             0x00000007
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_gpio_002_SHIFT            0

/***************************************************************************
 *PIN_MUX_CTRL_4 - Pin mux control register 4
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: reserved0 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_reserved0_MASK            0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_reserved0_SHIFT           30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: gpio_021 [29:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_021_MASK             0x38000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_021_SHIFT            27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: gpio_020 [26:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_020_MASK             0x07000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_020_SHIFT            24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: gpio_019 [23:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_019_MASK             0x00e00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_019_SHIFT            21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: gpio_018 [20:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_018_MASK             0x001c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_018_SHIFT            18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: gpio_017 [17:15] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_017_MASK             0x00038000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_017_SHIFT            15

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: gpio_016 [14:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_016_MASK             0x00007000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_016_SHIFT            12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: gpio_015 [11:09] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_015_MASK             0x00000e00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_015_SHIFT            9

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: gpio_014 [08:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_014_MASK             0x000001c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_014_SHIFT            6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: gpio_013 [05:03] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_013_MASK             0x00000038
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_013_SHIFT            3

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: gpio_012 [02:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_012_MASK             0x00000007
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_gpio_012_SHIFT            0

/***************************************************************************
 *PIN_MUX_CTRL_5 - Pin mux control register 5
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: reserved0 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_reserved0_MASK            0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_reserved0_SHIFT           30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: gpio_031 [29:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_031_MASK             0x38000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_031_SHIFT            27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: gpio_030 [26:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_030_MASK             0x07000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_030_SHIFT            24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: gpio_029 [23:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_029_MASK             0x00e00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_029_SHIFT            21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: gpio_028 [20:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_028_MASK             0x001c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_028_SHIFT            18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: gpio_027 [17:15] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_027_MASK             0x00038000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_027_SHIFT            15

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: gpio_026 [14:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_026_MASK             0x00007000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_026_SHIFT            12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: gpio_025 [11:09] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_025_MASK             0x00000e00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_025_SHIFT            9

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: gpio_024 [08:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_024_MASK             0x000001c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_024_SHIFT            6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: gpio_023 [05:03] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_023_MASK             0x00000038
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_023_SHIFT            3

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: gpio_022 [02:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_022_MASK             0x00000007
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_gpio_022_SHIFT            0

/***************************************************************************
 *PIN_MUX_CTRL_6 - Pin mux control register 6
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: reserved0 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_reserved0_MASK            0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_reserved0_SHIFT           30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: gpio_041 [29:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_041_MASK             0x38000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_041_SHIFT            27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: gpio_040 [26:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_040_MASK             0x07000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_040_SHIFT            24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: gpio_039 [23:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_039_MASK             0x00e00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_039_SHIFT            21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: gpio_038 [20:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_038_MASK             0x001c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_038_SHIFT            18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: gpio_037 [17:15] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_037_MASK             0x00038000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_037_SHIFT            15

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: gpio_036 [14:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_036_MASK             0x00007000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_036_SHIFT            12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: gpio_035 [11:09] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_035_MASK             0x00000e00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_035_SHIFT            9

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: gpio_034 [08:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_034_MASK             0x000001c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_034_SHIFT            6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: gpio_033 [05:03] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_033_MASK             0x00000038
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_033_SHIFT            3

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: gpio_032 [02:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_032_MASK             0x00000007
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_032_SHIFT            0

/***************************************************************************
 *PIN_MUX_CTRL_7 - Pin mux control register 7
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: reserved0 [31:31] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_reserved0_MASK            0x80000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_reserved0_SHIFT           31

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_054 [30:29] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_054_MASK             0x60000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_054_SHIFT            29

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_053 [28:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_053_MASK             0x18000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_053_SHIFT            27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_052 [26:25] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_052_MASK             0x06000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_052_SHIFT            25

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_051 [24:23] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_051_MASK             0x01800000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_051_SHIFT            23

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_050 [22:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_050_MASK             0x00600000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_050_SHIFT            21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_049 [20:19] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_049_MASK             0x00180000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_049_SHIFT            19

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_048 [18:17] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_048_MASK             0x00060000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_048_SHIFT            17

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_047 [16:15] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_047_MASK             0x00018000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_047_SHIFT            15

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_046 [14:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_046_MASK             0x00007000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_046_SHIFT            12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_045 [11:09] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_045_MASK             0x00000e00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_045_SHIFT            9

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_044 [08:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_044_MASK             0x000001c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_044_SHIFT            6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_043 [05:03] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_043_MASK             0x00000038
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_043_SHIFT            3

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_042 [02:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_042_MASK             0x00000007
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_042_SHIFT            0

/***************************************************************************
 *PIN_MUX_CTRL_8 - Pin mux control register 8
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: reserved0 [31:31] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_reserved0_MASK            0x80000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_reserved0_SHIFT           31

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_066 [30:28] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_066_MASK             0x70000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_066_SHIFT            28

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_065 [27:25] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_065_MASK             0x0e000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_065_SHIFT            25

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_064 [24:22] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_064_MASK             0x01c00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_064_SHIFT            22

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_063 [21:19] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_063_MASK             0x00380000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_063_SHIFT            19

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_062 [18:16] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_062_MASK             0x00070000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_062_SHIFT            16

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_061 [15:13] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_061_MASK             0x0000e000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_061_SHIFT            13

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_060 [12:10] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_060_MASK             0x00001c00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_060_SHIFT            10

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_059 [09:08] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_059_MASK             0x00000300
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_059_SHIFT            8

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_058 [07:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_058_MASK             0x000000c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_058_SHIFT            6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_057 [05:04] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_057_MASK             0x00000030
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_057_SHIFT            4

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_056 [03:02] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_056_MASK             0x0000000c
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_056_SHIFT            2

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_055 [01:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_055_MASK             0x00000003
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_055_SHIFT            0

/***************************************************************************
 *PIN_MUX_CTRL_9 - Pin mux control register 9
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: reserved0 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_reserved0_MASK            0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_reserved0_SHIFT           30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_076 [29:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_076_MASK             0x38000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_076_SHIFT            27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_075 [26:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_075_MASK             0x07000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_075_SHIFT            24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_074 [23:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_074_MASK             0x00e00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_074_SHIFT            21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_073 [20:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_073_MASK             0x001c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_073_SHIFT            18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_072 [17:15] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_072_MASK             0x00038000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_072_SHIFT            15

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_071 [14:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_071_MASK             0x00007000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_071_SHIFT            12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_070 [11:09] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_070_MASK             0x00000e00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_070_SHIFT            9

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_069 [08:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_069_MASK             0x000001c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_069_SHIFT            6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_068 [05:03] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_068_MASK             0x00000038
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_068_SHIFT            3

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_067 [02:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_067_MASK             0x00000007
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_067_SHIFT            0

/***************************************************************************
 *PIN_MUX_CTRL_10 - Pin mux control register 10
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: reserved0 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_reserved0_MASK           0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_reserved0_SHIFT          30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_086 [29:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_086_MASK            0x38000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_086_SHIFT           27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_085 [26:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_085_MASK            0x07000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_085_SHIFT           24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_084 [23:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_084_MASK            0x00e00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_084_SHIFT           21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_083 [20:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_083_MASK            0x001c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_083_SHIFT           18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_082 [17:15] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_082_MASK            0x00038000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_082_SHIFT           15

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_081 [14:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_081_MASK            0x00007000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_081_SHIFT           12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_080 [11:09] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_080_MASK            0x00000e00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_080_SHIFT           9

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_079 [08:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_079_MASK            0x000001c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_079_SHIFT           6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_078 [05:03] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_078_MASK            0x00000038
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_078_SHIFT           3

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_077 [02:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_077_MASK            0x00000007
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_077_SHIFT           0

/***************************************************************************
 *PIN_MUX_CTRL_11 - Pin mux control register 11
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: reserved0 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_reserved0_MASK           0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_reserved0_SHIFT          30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_096 [29:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_096_MASK            0x38000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_096_SHIFT           27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_095 [26:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_095_MASK            0x07000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_095_SHIFT           24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_094 [23:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_094_MASK            0x00e00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_094_SHIFT           21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_093 [20:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_093_MASK            0x001c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_093_SHIFT           18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_092 [17:15] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_092_MASK            0x00038000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_092_SHIFT           15

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_091 [14:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_091_MASK            0x00007000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_091_SHIFT           12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_090 [11:09] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_090_MASK            0x00000e00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_090_SHIFT           9

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_089 [08:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_089_MASK            0x000001c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_089_SHIFT           6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_088 [05:03] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_088_MASK            0x00000038
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_088_SHIFT           3

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_087 [02:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_087_MASK            0x00000007
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_087_SHIFT           0

/***************************************************************************
 *PIN_MUX_CTRL_12 - Pin mux control register 12
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: reserved0 [31:31] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_reserved0_MASK           0x80000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_reserved0_SHIFT          31

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: gpio_107 [30:29] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_107_MASK            0x60000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_107_SHIFT           29

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: gpio_106 [28:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_106_MASK            0x18000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_106_SHIFT           27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: gpio_105 [26:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_105_MASK            0x07000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_105_SHIFT           24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: gpio_104 [23:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_104_MASK            0x00e00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_104_SHIFT           21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: gpio_103 [20:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_103_MASK            0x001c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_103_SHIFT           18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: gpio_102 [17:15] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_102_MASK            0x00038000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_102_SHIFT           15

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: gpio_101 [14:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_101_MASK            0x00007000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_101_SHIFT           12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: gpio_100 [11:09] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_100_MASK            0x00000e00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_100_SHIFT           9

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: gpio_099 [08:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_099_MASK            0x000001c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_099_SHIFT           6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: gpio_098 [05:03] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_098_MASK            0x00000038
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_098_SHIFT           3

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: gpio_097 [02:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_097_MASK            0x00000007
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_gpio_097_SHIFT           0

/***************************************************************************
 *PIN_MUX_CTRL_13 - Pin mux control register 13
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_13 :: reserved0 [31:23] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_reserved0_MASK           0xff800000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_reserved0_SHIFT          23

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_13 :: byp_sys9_clk [22:22] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_byp_sys9_clk_MASK        0x00400000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_byp_sys9_clk_SHIFT       22

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_13 :: sgpio_09 [21:20] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_09_MASK            0x00300000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_09_SHIFT           20

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_13 :: sgpio_08 [19:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_08_MASK            0x000c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_08_SHIFT           18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_13 :: sgpio_07 [17:16] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_07_MASK            0x00030000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_07_SHIFT           16

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_13 :: sgpio_06 [15:14] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_06_MASK            0x0000c000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_06_SHIFT           14

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_13 :: sgpio_05 [13:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_05_MASK            0x00003000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_05_SHIFT           12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_13 :: sgpio_04 [11:10] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_04_MASK            0x00000c00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_04_SHIFT           10

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_13 :: sgpio_03 [09:08] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_03_MASK            0x00000300
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_03_SHIFT           8

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_13 :: sgpio_02 [07:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_02_MASK            0x000000c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_02_SHIFT           6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_13 :: sgpio_01 [05:04] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_01_MASK            0x00000030
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_01_SHIFT           4

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_13 :: sgpio_00 [03:02] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_00_MASK            0x0000000c
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_sgpio_00_SHIFT           2

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_13 :: gpio_108 [01:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_108_MASK            0x00000003
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_13_gpio_108_SHIFT           0

#endif /* #ifndef BCHP_SUN_TOP_CTRL_H__ */

/* End of File */
